# trigger manualy
name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Step 1 complete!"
    - run: echo "Step 2 complete!"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'Ready for prod–ship it!'
        color: 'magenta'